name: "Build: Top 50k packages on npmjs"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'


permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"
  pages: "write"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Run grabber
        run: deno task run

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "NPM Ranking"
          files: |
            dist/list-package-names.json
            LICENSE
